CREATE DATABASE Actividad_1_Rocio_Cruz
USE ACTIVIDAD_1_ROCIO_CRUZ

CREATE TABLE COMPUTADORA (
	IdComputadora INT PRIMARY KEY NOT NULL,
	Nombre VARCHAR(250) NOT NULL,
	Precio MONEY NOT NULL,
	Fecha_Fabricacion DATETIME NOT NULL
);

SELECT * FROM COMPUTADORA